"""Add share_button to AppSettings

Revision ID: 3812b8c7a39d
Revises: 
Create Date: 2025-12-11 22:21:26.897897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3812b8c7a39d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_button', sa.Text(), nullable=True))
        batch_op.drop_column('theme')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('share_button')

    # ### end Alembic commands ###
