"""initial schema

Revision ID: affaaf4c29f2
Revises: 
Create Date: 2025-12-31 13:41:48.941121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'affaaf4c29f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
